import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const regulations = [
  {
    name: 'ISO/IEC 27001:2022',
    description: 'International standard for information security management systems (ISMS). Provides requirements for establishing, implementing, maintaining and continually improving an ISMS.',
    authority: 'ISO/IEC',
    country: 'International',
    region: 'Global',
    category: 'INFORMATION_SECURITY',
    version: '2022',
    effectiveDate: new Date('2022-10-25'),
    externalUrl: 'https://www.iso.org/standard/27001',
    status: 'ACTIVE',
    requirements: [
      { id: 'ISO27-4.1', title: 'Understanding the Organization and its Context', type: 'MANDATORY', priority: 'HIGH', desc: 'Determine external and internal issues relevant to the organization\'s purpose that affect its ability to achieve the intended outcomes of its ISMS.' },
      { id: 'ISO27-4.2', title: 'Understanding Needs and Expectations of Interested Parties', type: 'MANDATORY', priority: 'HIGH', desc: 'Identify interested parties relevant to the ISMS and their requirements.' },
      { id: 'ISO27-5.1', title: 'Leadership and Commitment', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Top management must demonstrate leadership and commitment with respect to the ISMS.' },
      { id: 'ISO27-6.1', title: 'Actions to Address Risks and Opportunities', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Plan actions to address information security risks and opportunities including risk assessment and treatment.' },
      { id: 'ISO27-7.2', title: 'Competence', type: 'MANDATORY', priority: 'MEDIUM', desc: 'Determine necessary competence of persons doing work under the organization\'s control that affects information security performance.' },
      { id: 'ISO27-8.1', title: 'Operational Planning and Control', type: 'MANDATORY', priority: 'HIGH', desc: 'Plan, implement, control, monitor and review processes needed to meet information security requirements.' },
      { id: 'ISO27-9.1', title: 'Monitoring, Measurement, Analysis and Evaluation', type: 'MANDATORY', priority: 'HIGH', desc: 'Evaluate the information security performance and the effectiveness of the ISMS.' },
      { id: 'ISO27-9.2', title: 'Internal Audit', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Conduct internal audits at planned intervals to provide information on whether the ISMS conforms to requirements.' },
      { id: 'ISO27-10.1', title: 'Continual Improvement', type: 'MANDATORY', priority: 'MEDIUM', desc: 'Continually improve the suitability, adequacy and effectiveness of the ISMS.' },
      { id: 'ISO27-A5', title: 'Organizational Controls (Annex A)', type: 'MANDATORY', priority: 'HIGH', desc: 'Policies for information security, roles and responsibilities, segregation of duties, contact with authorities.' },
    ],
  },
  {
    name: 'GDPR (General Data Protection Regulation)',
    description: 'EU regulation on data protection and privacy for all individuals within the EU and EEA. Also addresses export of personal data outside these areas.',
    authority: 'European Parliament',
    country: 'European Union',
    region: 'Europe',
    category: 'DATA_PRIVACY',
    version: '2016/679',
    effectiveDate: new Date('2018-05-25'),
    externalUrl: 'https://gdpr.eu',
    status: 'ACTIVE',
    requirements: [
      { id: 'GDPR-5', title: 'Principles Relating to Processing of Personal Data', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Lawfulness, fairness, transparency, purpose limitation, data minimisation, accuracy, storage limitation, integrity and confidentiality.' },
      { id: 'GDPR-6', title: 'Lawfulness of Processing', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Processing shall be lawful only if at least one legal basis applies including consent, contract, legal obligation.' },
      { id: 'GDPR-7', title: 'Conditions for Consent', type: 'MANDATORY', priority: 'HIGH', desc: 'Controller shall demonstrate that the data subject has consented to processing of their personal data.' },
      { id: 'GDPR-13', title: 'Information to be Provided – Data Collection', type: 'MANDATORY', priority: 'HIGH', desc: 'Provide transparent information to data subjects at the time of collecting personal data.' },
      { id: 'GDPR-17', title: 'Right to Erasure (Right to be Forgotten)', type: 'MANDATORY', priority: 'HIGH', desc: 'Data subject has the right to obtain erasure of personal data without undue delay.' },
      { id: 'GDPR-25', title: 'Data Protection by Design and Default', type: 'MANDATORY', priority: 'HIGH', desc: 'Implement data protection principles in an effective manner and integrate safeguards into processing.' },
      { id: 'GDPR-32', title: 'Security of Processing', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Implement appropriate technical and organisational measures to ensure security appropriate to the risk.' },
      { id: 'GDPR-33', title: 'Notification of Personal Data Breach', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Notify supervisory authority of a personal data breach within 72 hours of becoming aware of it.' },
      { id: 'GDPR-35', title: 'Data Protection Impact Assessment', type: 'MANDATORY', priority: 'HIGH', desc: 'Carry out DPIA where processing is likely to result in high risk to rights and freedoms of natural persons.' },
      { id: 'GDPR-37', title: 'Designation of Data Protection Officer', type: 'MANDATORY', priority: 'MEDIUM', desc: 'Designate a DPO where required based on the nature, scope, context and purposes of processing.' },
    ],
  },
  {
    name: 'SOX (Sarbanes-Oxley Act)',
    description: 'US federal law that sets requirements for all US public company boards, management and public accounting firms regarding financial reporting and internal controls.',
    authority: 'U.S. Congress / SEC',
    country: 'United States',
    region: 'North America',
    category: 'FINANCIAL',
    version: '2002',
    effectiveDate: new Date('2002-07-30'),
    externalUrl: 'https://www.sec.gov/spotlight/sarbanes-oxley.htm',
    status: 'ACTIVE',
    requirements: [
      { id: 'SOX-302', title: 'Corporate Responsibility for Financial Reports', type: 'MANDATORY', priority: 'CRITICAL', desc: 'CEO and CFO must certify the accuracy of financial statements and effectiveness of internal controls.' },
      { id: 'SOX-401', title: 'Disclosures in Periodic Reports', type: 'MANDATORY', priority: 'HIGH', desc: 'Financial statements shall not contain incorrect statements or omit material information.' },
      { id: 'SOX-404', title: 'Management Assessment of Internal Controls', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Annual report must contain internal control report stating responsibility for establishing adequate internal control structure.' },
      { id: 'SOX-409', title: 'Real-Time Issuer Disclosures', type: 'MANDATORY', priority: 'HIGH', desc: 'Disclose on a rapid and current basis information concerning material changes in financial condition or operations.' },
      { id: 'SOX-802', title: 'Criminal Penalties for Altering Documents', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Prohibits knowingly altering, destroying, or falsifying records with intent to obstruct an investigation.' },
      { id: 'SOX-906', title: 'Corporate Responsibility for Financial Reports (Criminal)', type: 'MANDATORY', priority: 'CRITICAL', desc: 'Criminal penalties for certifying false financial reports.' },
    ],
  },
