import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

// Add a custom font or just use defaults
// We'll use the default helvetica font for simplicity and robustness

interface ReportConfig {
  title: string;
  subtitle?: string;
  generatedBy?: string;
}

/**
 * Base configuration and helper for initializing a new PDF document
 * with standard PryroGRC headers and footers.
 */
function createBaseDocument(config: ReportConfig): jsPDF {
  // A4 size, portrait, millimeters
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Draw Header
  doc.setFillColor(15, 23, 42); // slate-900 (dark header bar)
  doc.rect(0, 0, pageWidth, 25, 'F');

  // PryroGRC Logo Text
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('PryroGRC', 14, 16);

  // Document Title
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text(config.title, 14, 40);

  // Subtitle / Meta info
  doc.setTextColor(100, 116, 139); // slate-500
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  let currentY = 48;
  if (config.subtitle) {
    doc.text(config.subtitle, 14, currentY);
    currentY += 6;
  }
  
  doc.text(`Generated Date: ${format(new Date(), 'MMMM dd, yyyy HH:mm')}`, 14, currentY);
  if (config.generatedBy) {
    doc.text(`Generated By: ${config.generatedBy}`, 14, currentY + 6);
  }

  // Draw Footer (We do this in a plugin for autoTable so it applies to all pages)
  const addFooter = (data: any) => {
    const str = `Page ${data.pageNumber} of ${data.pageCount || data.pageNumber}`;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(str, pageWidth - 14, pageHeight - 10, { align: 'right' });
    doc.text('Confidential & Proprietary - Do Not Distribute', 14, pageHeight - 10);
  };

  // Attach footer callback to document so it can be passed to autoTable
  (doc as any)._addFooter = addFooter;

  return doc;
}

/**
 * Generates a PDF Report of all Findings
 */
export function generateFindingReport(findings: any[], generatedBy?: string) {
  const doc = createBaseDocument({
    title: 'Findings Summary Report',
    subtitle: 'Comprehensive list of all audit findings and their current status.',
    generatedBy,
  });

  const tableData = findings.map(f => [
    f.findingNumber,
    f.audit?.auditNumber || '-',
    f.title,
    f.severity,
    f.status,
    f.owner ? `${f.owner.firstName} ${f.owner.lastName}` : 'Unassigned',
    f.dueDate ? format(new Date(f.dueDate), 'MMM dd, yyyy') : '-',
  ]);

  autoTable(doc, {
    startY: 65,
    head: [['Finding ID', 'Audit', 'Title', 'Severity', 'Status', 'Owner', 'Due Date']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42], textColor: 255 },
    styles: { fontSize: 8, cellPadding: 3 },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 25 },
      2: { cellWidth: 'auto' },
      3: { cellWidth: 20 },
      4: { cellWidth: 25 },
      5: { cellWidth: 30 },
      6: { cellWidth: 25 },
    },
    didDrawPage: (data) => (doc as any)._addFooter(data),
  });

  doc.save(`Findings_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
}

/**
 * Generates an Executive Audit Report
 */
export function generateAuditReport(audit: any, findings: any[], generatedBy?: string) {
  const doc = createBaseDocument({
    title: 'Audit Executive Summary',
    subtitle: `${audit.auditNumber} - ${audit.title}`,
    generatedBy,
  });

  let currentY = 65;

  // Audit Details Section
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Audit Details', 14, currentY);
  
  currentY += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);

  const details = [
    ['Type:', audit.type],
    ['Status:', audit.status],
    ['Department:', audit.department || 'N/A'],
    ['Start Date:', audit.startDate ? format(new Date(audit.startDate), 'MMM dd, yyyy') : '-'],
    ['End Date:', audit.endDate ? format(new Date(audit.endDate), 'MMM dd, yyyy') : '-'],
    ['Lead Auditor:', audit.leadAuditor ? `${audit.leadAuditor.firstName} ${audit.leadAuditor.lastName}` : '-'],
  ];

  details.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, currentY);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 45, currentY);
    currentY += 6;
  });

  // Objective & Scope
  currentY += 4;
  if (audit.objective) {
    doc.setFont('helvetica', 'bold');
    doc.text('Objective:', 14, currentY);
    doc.setFont('helvetica', 'normal');
    const splitObj = doc.splitTextToSize(audit.objective, 180);
    doc.text(splitObj, 14, currentY + 5);
    currentY += 5 + (splitObj.length * 5);
  }

  if (audit.scope) {
    currentY += 4;
    doc.setFont('helvetica', 'bold');
    doc.text('Scope:', 14, currentY);
    doc.setFont('helvetica', 'normal');
    const splitScope = doc.splitTextToSize(audit.scope, 180);
    doc.text(splitScope, 14, currentY + 5);
    currentY += 5 + (splitScope.length * 5);
  }

  // Findings Summary Table
  currentY += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Identified Findings', 14, currentY);

  if (findings.length === 0) {
    currentY += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('No findings recorded for this audit.', 14, currentY);
    // Render footer manually since we aren't calling autoTable
    (doc as any)._addFooter({ pageNumber: 1, pageCount: 1 });
  } else {
    const tableData = findings.map(f => [
      f.findingNumber,
      f.title,
      f.severity,
      f.status,
    ]);

    autoTable(doc, {
      startY: currentY + 5,
      head: [['ID', 'Title', 'Severity', 'Status']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      didDrawPage: (data) => (doc as any)._addFooter(data),
    });
  }

  doc.save(`${audit.auditNumber}_Audit_Report.pdf`);
}
